input {
  kb_layout = gb,it
  kb_options = caps:lock,grp:alts_toggle
}

# Dell ultrawide on the left (no scaling)
monitor=DP-1,3440x1440@59.97,0x0,1

# Laptop on the right (2x scaling for HiDPI)
monitor=eDP-1,2880x1920@120,3440x600,2
