input {
  kb_layout = gb,it
  kb_options = caps:lock,grp:alts_toggle
}

# Laptop on the right (2x scaling for HiDPI)
monitor=eDP-1,preferred,0x0,2
# Dell ultrawide on the left (no scaling)
monitor=DP-1,preferred,auto-left,1
# Acer on the left (no scaling)
monitor=DP-2,preferred,auto-left,1
